src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/internals/BulkProcessor.java

Also some slight cleanup around throwing `RetriableException` when `max.buffered.records` is hit

CC-301: Lower default values of `max.buffered.records` and `batch.size`

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java

The smallest of fixes :) So that instead of 
`org.apache.kafka.connect.errors.DataException: MAPis not supported as the document id.`
we get
`org.apache.kafka.connect.errors.DataException: MAP is not supported as the document id.`
It looks better, and makes for easier Googling!

Add space at front of error message text

---

.gitignore
docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnector.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java

Rewrote some of the config option docs for clarity and addressed comments from https://github.com/confluentinc/kafka-connect-elasticsearch/pull/31

CC-331: update config options docs

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTestBase.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

@kkonstantine this is a first run at fixing map output for String keyed maps. Things I know are problematic currently:
1. `MappingTest` ends up with a StackOverflowException because we are recursing on a map of strings in that test. Still looking into that.
2. We should decide if only String keyed maps should behave this way. I'm not sure what the ES standard is.
3. One weird thing I found was that if in `DataConverterTest.stringKeyedMap` I use a BigDecimal for validation instead of an INT32, I have a hard time validating the map values because the `DataConverter.preProcessValues` returns a `Double` object instead of a `BigDecimal` as I would expect it to. This seems to be consistent with and without my changes, so it's good to verify if that's expected behavior.

Fix map output for String keyed maps

---

docs/configuration_options.rst
docs/elasticsearch_connector.rst
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/RetryUtil.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/test/java/io/confluent/connect/elasticsearch/RetryUtilTest.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

With lots of ES connector tasks all hitting the ES backend, when the ES backend becomes overloaded all of the tasks will experience timeouts (possibly at nearly the same time) and thus retry. Prior to this change, all tasks would use the same constant backoff time and would thus all retry at about the same point in time and possibly overwhelming the ES backend. This is known as a thundering herd, and when many attempts fail it takes a long time and many attempts to recover.
A solution to this problem is to use expontential backoff to give the ES backend time to recover, except that this alone doesn’t really reduce the thundering herd problem. To solve both problems we use expontential backoff but with jitter, which is a randomization of the sleep times for each of the attempts. This PR …

CC-1059 Changed ES connector to use exponential backoff with jitter

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTestBase.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

Prior to 3.3.0, all map entries were serialized into JSON using a less compact form like the following that worked for all types of keys:
```
"metadata" : [ 
{ 
"key" : "lastUpdated", 
"value" : "20170209-23:58:26.420" 
}, { 
"key": "isSoftDeleted", 
"value": "false" 
}
...
]
```
In 3.3.0 this was changed so that the entries of all maps with string keys were written out in a more compact and natural JSON representation:
```
"metadata" : { 
"lastUpdated": "Tue Feb 07 20:57:05 GMT 2017", 
"isSoftDeleted": "false", 
...
}
```
Now, a new `compact.map.entries` configuration property allows users to control this behavior. This configuration defaults to `true` to match the newer 3.3.0 behavior for the entries of maps with string keys. However, simply set `compact.map.entries=false` for the …

CC-1191: Added feature flag to control string-keyed map entry JSON serialization

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java

Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-190: Deprecate the topic.index.map configuration option

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/BulkIndexingClient.java
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/IndexableRecord.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTestBase.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

Added a configuration to control how records with null values (e.g., tombstone messages) are handled, with three options: `IGNORE`, `DELETE`, and `FAIL`.
The `FAIL` option is identical to the previous behavior. The `DELETE` option generates a corresponding delete operation in the Elasticsearch system only when the record has an explicit key; if `key.ignore` is true, the keys will be generated and delete does not make sense. And finally the `IGNORE` option tells the connector to quietly skip over any records that have a null value.
Although the previous behavior is equivalent to `FAIL`, that cause the connector for fail and stop whenever it came across a null value. A more sensible default is `IGNORE`.
NOTE: This is an alternative PR with nearly the same changes as #163 but with fewer …

CC-350, CC-1097: Added support for delete and null handling

---

.gitignore
docs/elasticsearch_connector.rst

https://confluentinc.atlassian.net/browse/DOCS-208
- related https://github.com/confluentinc/kafka-connect-elasticsearch/pull/169
Staging server http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/693/3.3.0/connect/connect-elasticsearch/docs/elasticsearch_connector.html#quick-start

DOCS-208 - Connect Elastic Quickstart not working

---

checkstyle/suppressions.xml
pom.xml
src/main/java/io/confluent/connect/elasticsearch/BulkIndexingClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConstants.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/IndexableRecord.java
src/main/java/io/confluent/connect/elasticsearch/Mapping.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkRequest.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestBulkRequest.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTestBase.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

The ES connector now queries for the version.  The version is stored in
an instance of ElasticsearchClient, which is passed around so that
it can be queried at the appropriate times (such as when inferring
schema mappings).
As part of this change, the old Jest client is now wrapped by a
higher-level client object.  Also, all the Jest dependencies have been
isolated to the io.confluent.connect.elasticsearch.jest package.  This
makes the third-party dependencies more clear and will facilitate moving
to a different ES client library in the future should we choose to do
so.
These changes have been tested with ES 2.x, 5.x, and 6.x.

CC-1385:  Enhance connector to use text type with ES 5+

---

docs/elasticsearch_connector.rst

Remove the note since we now support ES6.

CC-1491: Remove note about unsupported ES6 from ES quick start

---

docs/elasticsearch_connector.rst

Add note to state that `schema.ignore=true` can be added for ES6

CC-1550: Clarify ES 6 compatibility

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

This fixes a NullPointerException when a array, map, or struct is null
and the schema is optional with no default value.

CC-1625:  Fix NPE for null arrays with no default

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

If a `Struct` schema contains an optional field of type `Decimal`, `Array`, `Map`, or `Struct`, an NPE is thrown when converting values for this schema when the corresponding field is `null`. This PR provides a fix for that bug, including several unit tests to ensure it won't pop up again.
Additionally, in the process of fixing this NPE, we ran across another error that the NPE masked wherein passing a struct containing a `null` value for a field with an optional `Map` schema to the `DataConverter.preProcessValue(...)` method would cause a `DataException`. This is also addressed, specifically by adding a call to `copySchemaBasics(...)` to the `preProcessMapSchema(...)` method. This bug would _not_ have affected top-level optional maps, which helps explain why it has not yet been reported …

CC-1802 Handle null values in optional struct fields with no defaults

---

pom.xml

As mentioned in https://github.com/confluentinc/kafka-connect-elasticsearch/pull/243, we want to clarify that ES 6.x is supported by this connector as of version 4.1.0.

MINOR: Add 6.x to supported versions in Kafka Connect Maven Plugin configuration

---

pom.xml

The `module-info` files will appear in multiple JARs, and they are not duplicates. The ES JarHell utility that the Elasticsearch project uses in their tests and base classes for tests (which we inherit and use in our tests) doesn’t take the `module-info` files into account.
Luckily there is a way to disable this check in the tests via the `tests.jarhell.check=false` system property, which this commit changes in the Surefire configuration.

CC-3034: Disabled the ES JarHell utility since it considered `module-info` files as duplicates

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

As described in (https://github.com/confluentinc/kafka-connect-elasticsearch/issues/246#issuecomment-431794980), Elasticsearch can only create indexes in lowercase letters, this PR fix this by making sure that all indexes are created that way.
Please forgive me If I miss a necessary check before pushing the PR, is the first time I contribute a change. 
Fix partially #246 
Backport of #250 as requested in https://github.com/confluentinc/kafka-connect-elasticsearch/pull/250#pullrequestreview-167503044

[Backport ready] Fix bug when topic names are not in all lowercase

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

Builds on https://github.com/confluentinc/kafka-connect-elasticsearch/pull/270
Uses common Apache Kafka configs
Has a very basic unit test, but integration test framework here is for Elastic 2.x, which needs to be updated. The automated test here is taking a lot of time, and I'm trying to learn if integration test in this repo is better or system test external to this repo.
This has been manually tested. Automated integration or system tests will come, but Jest client does not integrate with elastic's provided integration test framework for elastic 6.x (required for xpack), so that would require an overhaul on the client. Could be done but is out of scope

Add HTTPS support to Elasticsearch connector

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

This PR include changes enhance the experience creating indexes in Elasticsearch based on the preferred index names and not only on the topic name.
Before this PR the connector create all indexes at start time, using the topic names as a basis for that. However there are situations when the users need to change the expected index name using an SMT. This PR include as well a backwards compatibility flag, so the users can decide if they aim to keep the initial bootstrap index creation time or disable it and rely only in the record write time operation.
Proposed flow:
1. By default: create always an initial topic to index during start time. This could be deactivated if necessary.
2. Make sure that if a SMT is applied, the index is created anyway. (this does not happen in the current way of …

Disable index creation at bootstrap time

---

pom.xml
src/test/java/io/confluent/connect/elasticsearch/integration/README.md

Packaging pipelines did not have docker daemons, so we will
run integration tests only in Jenkins profile which is guaranteed
to have a docker daemon, until a better tooling solution is
worked out.

Limit integration test to run only with "jenkins" mvn profile

---

Jenkinsfile

This is causing failures in the deployment:
https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.2.x/60/console
These fixes will also be merged upstream to `jenkins-common`, but this is a testing-ground.

MINOR: Give docker URI to deploy statements

---

pom.xml

A predefined default version is provided in the common pom so we default to using the most recent Scala version where possible and so we don't have to build all versions in some other cases (such as system tests).

ST-1492: Use predefined kafka.scala.version

---

src/main/java/io/confluent/connect/elasticsearch/Mapping.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

This PR remove the usage of null_values as part of the generated elasticsearch mappings for textual (searchable) fields. 
Before this PR, anyone willing to use text based fields need to create their mappings manually as the inferred one was wrong. As you can see from https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html#text-params, this option is not accepted for text fields.
this PR cleans up as well the problem for binary fields
fixes  #285 #132 #271 #99

CC-4054: Remove the use of null_value (default values) for text and binary based fields

---

pom.xml

ES has a test dependency `jackson-core:2.8.1` which has a vulnerability described here - https://nvd.nist.gov/vuln/detail/CVE-2018-19362.
This PR excludes it from packaging.

SEC-168: Exclude jackson-core from packaging.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/SecurityProtocol.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/SecurityIT.java

Relying on `connection.url` is not sufficient in some case, e.g. when users have configured Worker to talk to ES, which is behind proxy, and proxy terminates SSL and uses plaintext.
This PR adds an additional configuration parameter, `elastic.security.protocol`, with two possible values: `PLAINTEXT`(default) and `SSL` which should be already known to users.

CC-4788: Added elastic.security.protocol.

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

This PR handles version conflicts for upsert use-case when a topic has multiple partitions and there is no guarantee that messages with the same ids will be written to the same partition.
We are assuming that when we use a user-provided key(`ignoreKey=false`), all messages with the same id are produced to the same partition, thus we use message's offset as version when writing a document to ES.
Example:
User has a topic `moon` with 10 partitions, and produces a message `{"entityId": "42": "color": "red"}`, it gets written to partition 1, with offset 50.
💚 ES Connector sends a document to ES: `Key:42, Version:50, Payload:{"color": "red"}`.
Then, the next message with the same id is produced `{"entityId": "42": "color": "red"}`, it gets written to partition 2, with offset 30.
🔴 ES Connector …

CC-5605: Log version conflicts as warnings.

---

src/test/java/io/confluent/connect/elasticsearch/integration/SecurityIT.java

This test fails on Jenkins because of invalid certs, so the tests cannot actually connect to the Docker container when running on Jenkins. Still investigating a solution, but in the meantime, here’s a temporary fix.

CC-4886: Temporarily ignore SecurityIT

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

If an already existing index is not cached in JestElasticsearchClient, performance will decrease.  For instance, the difference could be 3000 documents per second written in the elasticsearch when the preexisting index is not cached, versus 9000 documents per seconds if the index is cached.
Commit imported from the original [PR](https://github.com/confluentinc/kafka-connect-elasticsearch/pull/309)
had to rebase to point at the 4.1.x branch instead of master

CC-6187: Cache already existing index in JestElasticsearchClient

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

This code uses jest-http client that's supported Gzip compression over HTTP and this commit introduced an option to control this compression.
By default compression is disabled and this doesn't change any behaviour until it is enabled by hand.

CC-7146 : Introduce an option to control HTTP-level compression

---

checkstyle/suppressions.xml
pom.xml
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/LogContext.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchSinkTaskIT.java
src/test/resources/log4j.properties

Some logging was added at INFO level when it would not occur under nominal operation, more at DEBUG level to identify what the connector is doing and when while still not writing individual record details, and a few more at TRACE that output which messages are being processed.
I tried to be a bit conservative in terms of the log level, so as to not overwhelm the log during normal or even debug operation.

CC-7367: Add a lot more logging

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/jest/actions/PortableJestCreateIndexBuilder.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

Currently, the connector has retry mechanism for the actual writes and doesn't do retries for create index.
https://confluentinc.atlassian.net/browse/ESCALATION-2214. 
In cases where elastic has a temporary glitch this leads to connector failing. Adding a retry mechanism using the same configs that are already exposed.
- Retry on IO Exception ( potentially happening because of client timeout)
- Retry on a failure response ( this is an area to be improved). ES could also timeout on server side  and we would want to retry in those situations
- pass timeout on the create index API call

ESCALATION-2214 : Add retries for create index

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java

Background: I have "key.ignore=false" and have old messages in my topic that don't have keys or have empty keys. Connector tasks fail because Elasticsearch is returning a validation error:
{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}
Ignore errors like this so tasks don't stop running. Addig "action_request_validation_exception" to the list covered by "behavior.on.malformed.documents".

Make "behavior.on.malformed.documents" also cover "action_request_validation_exception" (#325)

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

Changes:
1. Add config max.connection.idle.time.ms for taking value from connector config, default value 60s. 
1. Since check style didn't allow method more than 150 lines, I separated the method into "addConnectorConfigs" and "addConnectorTimeoutConfigs". Not sure if this is good practice, need review for that.
1. put the maxConnectionIdleTime parameter to config builder

Add configuration for Max connection idle time to prevent read timeout

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java

Tests were failing due to use of deprecated `ExpectedException.none()`. We picked up the new version of JUnit that deprecated this in: 
https://github.com/confluentinc/common/commit/10fef4a03b21fc6c4aaad6948bcc1386fcdcc26d
Just switch over to use assertThrows as suggested in JUnit release notes - https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.13.md#pull-request-1633-deprecate-expectedexceptionnone

MINOR: Fix tests

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

The `SslFactory` class in Apache Kafka was recently changed and no longer includes `sslEngineBuilder()`. The `SslEngineBuilder` class has also been removed from Apache Kafka and a new class, `SslEngineFactory` is being used instead. There wasn't a clean way to leverage the new API to provide an `SSLContext` to the ElasticSearch connector, so instead I copied the code from AK into the connector.
Signed-off-by: Aakash Shah <ashah@confluent.io>

CC-8869: Fix kafka sslfactory changes causing ES connector to break

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/HostnameVerificationDisabledIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/SecurityIT.java
src/test/resources/ssl/instances.yml

When `elastic.https.ssl.endpoint.identification.algorithm` is empty, instead
of default hostname verifier, use an all-trusting verifier.
Updated SecurityIT with testcase to verify

CC-9314: Allow disabling hostname verification

---

src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

During executor shutdown, it attempts to terminate existing tasks by sending interrupts to the threads. The `Time.sleep` that we use to sleep between retry attempts wraps around AK `Utils.sleep` that handles the `InterruptedException` by setting `Thread.currentThread().interrupt()`. We just need to inspect the interrupted state of current thread before making our next retry attempt.

CC-9347: Inspect interrupted state before next attempt

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchSinkTaskIT.java

the connector currently can fail/ignore records that are malformed on the ES side. Reporting them using the new AK 2.6 reporter feature would be beneficial.
Add the AK 2.6 reporter DLQ feature
modify unit tests to check whether the reporter is called
this is a new feature therefore pushing to `master`

CC-7635: implement DLQ reporter for malformed doc records

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

Sometimes the response from the ES server does not have the "nodes" element we expect to parse, and we get an NPE when we should be returning default version. 
I added some more look-before-you-leap logic to log a warning and return default.
Alternative proposal: Wrap the whole function in blanket try-catch and return default version. I considered this to just put this to rest once and for all, but decided this would be faster and less controversial.
Will target 5.1.x which is the earliest one that has logic kind of like this.

Check for unexpected datatypes in response from server

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java

the reporter will fail with `NoSuchMethodFoundError` on old Connect workers. 
add `NoSuchMethodFoundError` to the try catch
https://cwiki.apache.org/confluence/display/KAFKA/KIP-610%3A+Error+Reporting+in+Sink+Connectors
unfortunately I do not see a way that this can be tested. If anyone has suggestions, I will gladly implement. 
edit: I have run a manual test using CP 5.5.0 which runs on AK < 2.6 and the connector runs
`master` where this feature was first implemented

fix reporter to catch NoSuchMethodFoundError as well

---

Jenkinsfile
pom.xml

We need the release maven plugin for independent releases. Also, some adjustment in version variables
Add the plugin and apply fixes
In all community available connectors formerly shipping with CP
master only. 10.0.x will be created after this commit.

CC-11857: Add release maven plugin and prepare 10.0 release

---

src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

the connector has to keep an internal map (`recordMap`) to keep track of the original `SinkRecords` so that it can report any errors using the DLQ reporter. the connector has been experiencing a memory leak first noticed in #444. On further analysis it was found that the connector did not empty the map on successful writes (only on [failed writes](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java#L478)).
empty the map correctly in all cases
modified all existing unit tests to verify that the map is indeed empty
backport to `10.0.x` where the DLQ reporter was first introduced

CC-11959: BulkProcessor does not empty internal record map correctly

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchSinkTaskIT.java

connector does not use config getters which is not the best practice and ends up with some clunky code
add config getters and reorganize config class
ensure all previous tests pass
backport to `5.0.x` to reduce pint merge conflicts in future PRs

MINOR: clean up and add getters to config

---

checkstyle/suppressions.xml
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkProcessor.java
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkResponse.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestBulkRequest.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

the reporter currently reports all records in a batch as failed if even 1 record failed due to the connector design. This is incorrect and produces a lot of unnecessary logs as well.
refactor the reporter to only report failed records in failed batches
write unit test to make sure only failed records are written
backport to `10.0.x` when reporter was first introduced

CC-11969: do not report successful records in failed batches

---

src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

[Jira](https://confluentinc.atlassian.net/browse/CC-12066)
Flaky test that fails every once in a while due to a benign race condition. Some failures include:
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.3.x/327
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.3.x/339
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.4.x/261
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.4.x/265
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.5.x/195
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearch/job/5.5.x/205
- https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-elasticsearc …

CC-12066: Fix flaky test BulkProcessorTest::farmerTaskPropogatesException

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

index exists can return a 404 Not Found when it exists
check that the reason index creation failed was because it already exists and only then check if the index exists
add unit test to mock a failed index creation
backport where this was first introduced

CC-12129: catch resource_already_exists_exception when creating indices

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/bulk/BulkProcessorTest.java

the worker calls `SinkTask::close` followed by `SinkTask::flush`, but `SinkTask::close` closes the `BulkProcessor` which causes the consequent flush to throw an exception.
only flush if the `BulkProcessor is still open
write a test that flushes after close
backport as far back as possible

CC-12530: do not throw exception on flush after task close

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

test is throwing NPE due to the reporter in `10.0.x`
mock context
rerun tests
backport to `10.0.x` where test breaks

MINOR: fix test/build

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnector.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

the connector does not validate config combinations at all
config combinations for ssl, proxy, and connectivity will come in later PRs
add config combo validations
other branches for configs added there i.e proxy and ssl
new unit tests that test both valid and invalid configs
backport to `5.0.x` and then add more validators in follow up PRs

CC-12452: add config combination validators 

---

src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

the connector does not validate different combinations of SSL configs
add validator to validate that SSL configs are only specified when elasticsearch.security.protocol is set to `SSL`
proxy and connection configs need to be validated as well
add unit tests for both valid and invalid combinations for ssl configs
backport to `5.2.x` where the ssl configs were introduced

CC-12621: add config combo validator for ssl configs

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

the connector has no validators whatsoever for configs
add basic common sense validators
added a few unit tests to test the validators
`master` to get all of the configs and then will backport to older branches

CC-10923: add reasonable validators for configs

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

need to backport reasonable validators for numbered configs #456 
backport to `5.0.x`
all branches up to `master`
backport to `5.0.x`

CC-10923: add reasonable validators for number configs

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

config combo validations for proxy should be moved to combo validator class
move them there
unit tests
backport to where these validators were first introduced `10.0.x`

MINOR: move proxy validators to validator class

---

licenses.html
pom.xml

This PR addresses the problem that you can't currently build the `5.5.1-post` branch (and I think other branches equally) with a clean Maven cache and the repositories as-defined.
The `<repository>` definition relies on property `confluent.maven.repo` for `url`.  This is a problem when resolving the parent POM, since Maven resolves the parent before local properties.
Typical error:
```
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/common/5.5.0/common-5.5.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:5.5.0: Could not transfer artifact io.confluent:common:pom:5.5.0 from/to confluent (${confluent.maven.repo}): Cannot …
```

MINOR: Removed property ${confluent.maven.repo} from the pom repository

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java

`topic.index.map` is deprecated and is set to be removed for the upcoming jest client replacement work #468 
remove the config
update the docs to mark this config as removed
N/A - verify existing tests still pass
`master` to a new major version because this breaks backward compatibility

CC-12597: remove topic.index.map

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

`auto.create.index.at.start` is an obsolete config and the connector should permanently function as if `auto.create.index.at.start=false`
remove the config
remove old test and modify existing test to make sure index is still being created properly
`master` and bump to `11.0.x` because breaking backward compatibility

CC-12825: remove auto.create.index.at.start config

---

checkstyle/suppressions.xml
pom.xml
src/main/java/io/confluent/connect/elasticsearch/ClientConfigCallbackHandler.java
src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosWithSslIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorSslIT.java
src/test/resources/both/elasticsearch.yml
src/test/resources/both/instances.yml
src/test/resources/both/start-elasticsearch.sh
src/test/resources/kerberos/elasticsearch.yml
src/test/resources/kerberos/instances.yml

the connector does not support kerberos authentication
implement kerberos authentication, built on top of #468 
new feature hence `master`, building on top of #468

CC-8546: add Kerberos support

---

pom.xml

Confluent Hub documentation links not redirecting properly.
Update pom.mxl with correct path to docs page

Update pom.mxl with correct path to docs page

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

We need to be more lax on the qualifiers we accept in versions
Fix regex

MINOR: Fix semver test to correctly accept qualifiers in the end

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java

data sets that have frequent updates will result in slow performance because of long wait times
reduce the wait times to 10ms to fix performance bottlenecking
remove the unique constraint by relying on `BulkItemResponse::getItemId` which returns the order of the request in the bulk request, which we can use to map the request to the `SinkRecord` it came from
modified a test to upsert multiple records with the same key
existing reporter tests cover the rest of the test cases
PERF TEST RESULTS:
configs
```
{
"task.max": 1,
"linger.ms": 1000,
"batch.size": 2000,
"max.buffered.records": 20000,
"max.in.flight.requests": 5,
}
```
v10.0.2 with the same key for every single record
a steady 6.7K records/s
this PR:
the first rate is a steady 32K …

CCMSG-796: fix poor performance for lots of update requests

---

pom.xml

There is a CVE in HttpClient brought in by io.searchbox:jest:jar:6.3.1. We need to upgrade it to HttpClient. 
I am trying to add a direct dependency on HttpClient. It seems that 5.0.x and 5.1.x 's tests will not pass even without this change. 
Rely on existing tests and let's discuss whether additional tests are needed.
Merging to master.

CC-13829: Upgrade httpclient to 4.5.13

---

src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java

the connector does not set the `read.timeout.ms` config correctly for socket timeouts
set the socket timeout correctly with the config
backport to `11.0.x` where this bug was introduced

CCMSG-836: Connector does not set 'read.timeout.ms' correctly

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

we are missing a validator whether the ES service is available
add a validator by pinging ES
add unit tests testing the validator, existing ITs also run the added code
backport to `11.0.x` where this validaator should be added

CCMSG-201: add connection configs validator

---

pom.xml

Shown by the mvn dependency:tree command, the httpclient dependency drags in commons-codec to 1.11, which is marked by twistlock as a vulnerability
Exclude the dependency from httpclient, and bump to the latest version (1.15).
It also applies to 5.5.x, so but it should be fixed in the backport of this PR.
mvn verify and mvn integration-test to make sure nothing broke
targeting 5.4.x

CCMSG-835, CCMSG-834: Update outdated commons-codec to fix CVE

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/NetworkErrorContainer.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosWithSslIT.java

the retries provided by Elasticsearch client are not adequate enough to cover network errors
https://github.com/elastic/elasticsearch/issues/71159
implement retries for network errors
if a bulkrequest fails, then retry it in the same request thread 
add a test that adds a network delay to the ES container and make sure the client is still able to write
backport to `11.0.x` since this is a regression

CCMSG-920: add retries to bulk requests

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

Data streams requires configurations for the `type` and `dataset`
Those 2 configurations were added along validation to ensure `dataset` follows the restrictions for data stream and index names specified by Elastic. 
[data stream fields restrictions](https://github.com/elastic/ecs/blob/master/rfcs/text/0009-data_stream-fields.md)
[index name restrictions](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params)
Will be released as part of the whole datastream feature.
Not backporting or merging to master.

CCMSG-965: Add necessary configs for Elasticsearch datastreams

---

Jenkinsfile
checkstyle/suppressions.xml
pom.xml
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java

Elasticsearch connector does not allow writes to data streams.
Extended functionality to alternatively allow writes to data stream if the data stream configurations are set.
Will be released as part of the data stream feature.
Not backporting or merging to master.

CCMSG-966: Implement data stream write for Elasticsearch

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

When writing records to regular elasticsearch indices, external versioning ensures only the latest record with the same key ends up in elasticsearch. However, external versioning is not supported for data stream as mentioned in [Elasticsearch's index API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#docs-index_). 
Currently, external versioning is set for records with the same key regardless of whether data stream is enabled. This causes the Bulk Request to fail with the error
`org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: create operations only support internal versioning. use index instead`
Prevent updating the versioning type and version number if data streams is enabled. If messages with the same key …

CCMSG-1116: Prevent adding external versioning to data stream.

---

pom.xml

https://issues.apache.org/jira/browse/MNG-7118
high version maven block HTTP repositories by default
```
[ERROR] Failed to execute goal on project kafka-connect-elasticsearch: Could not resolve dependencies for project io.confluent:kafka-connect-elasticsearch:jar:5.5.2: Failed to collect dependencies at org.apache.kafka:connect-api:jar:7.0.0-87-ccs: Failed to read artifact descriptor for org.apache.kafka:connect-api:jar:7.0.0-87-ccs: 
Could not transfer artifact org.apache.kafka:connect-api:pom:7.0.0-87-ccs from/to maven-default-http-blocker (http://0.0.0.0/): 
Blocked mirror for repositories: [confluent (http://packages.confluent.io/maven/, default, releases+snapshots)] -> [Help 1]
```
change pom.yml
use ```            <url>https://packages.confluent.io/maven/</url>``` instead of ``` …
```

use https confluent maven repo

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/EnumRecommender.java

The enum configs are set by filling in the blank which requires users to review the config descriptions for what the values are and which configs have specific values.
Add a recommender to each of those configurations such that it recommends the specific values.
The `data.stream.type` config could also use a recommender. (#531)
After adding the recommenders, checked in confluent platform that those configs had the correct recommenders and that the configs are settable.
Backporting to 11.0.x, which is the oldest version still being supported.
Not backporting or merging to master.

CCMSG-1119: Add drop down menus for the existing enum configs.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java

In confluent platform, there are specific values a user can choose from for setting the `data stream type`. However, currently, this configuration is set by filling in the blank which requires users to review the config description to remember what the values are and which configs have specific values.
Add a recommender to each of those configurations such that it recommends the specific values.
Added the recommenders and checked in confluent platform that those configs had the correct recommenders.
Releasing as part of the data stream feature.
Not backporting or merging to master.

CCMSG-1115: Add a dropdown menu to setting the data stream type config.

---

pom.xml

Commons-codec had unresolved CVE's
Upgrade commons-codec to 1.15
Upgrade ES client to latest bugfix version

Address CVEs by upgrading commons-codec to 1.15

---

pom.xml

snakeyaml dependency was missing causing build failures
Pin snakeyaml to 1.28

Fix breaking builds by pinning snakeyaml to 1.28

---

src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

We call `org.elasticsearch.client.RestHighLevelClient#ping` in `io.confluent.connect.elasticsearch.Validator#validateConnection` and we are catching `IOException` only.
But `RestHighLevelClient` can throw `ElasticsearchStatusException` as well, which results in the validate endpoint returning HTTP 500.
Catch `ElasticsearchStatusException` to avoid throwing `500`.

CCMSG-1137: Handle ElasticsearchStatusException in validateConnection.

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

The `@timestamp` field is needed in messages to send them to data stream. Currently, the `@timestamp` field is auto-injected with the record timestamp if it is missing. However, users may not want to inject the `@timestamp` field and may instead want those records to fail. Injecting the `@timestamp` field should only happen if records have no timestamp value at all. Otherwise, having both sets of values (the original `@timestamp` value and the injected value) would be confusing. 
Additionally, field names with special characters are not allowed in [Avro](http://avro.apache.org/docs/current/spec.html#names) and Protobuf, meaning users with Avro or Protobuf schemas can not have an `@timestamp` field. 
Since both of these issues relate to the `@timestamp` field, we can add one connector …

CCMSG-1135: Create a config that handles mapping to the @timestamp field.

---

Jenkinsfile
checkstyle/suppressions.xml
pom.xml
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java

Elasticsearch recently release a new feature called Data Streams. 
This PR allows the connector to alternatively write to a data stream and is the accumulation of many smaller PRs that have been approved over time.
Releasing on-premise and on-cloud.
Yes, merging into master.

CCMSG-961: Elasticsearch Datastreams

---

README.md
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosWithSslIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorSslIT.java
src/test/resources/basic/elasticsearch.yml
src/test/resources/basic/instances.yml
src/test/resources/both/start-elasticsearch.sh

After we introduced `io.confluent.connect.elasticsearch.Validator#validateConnection` method, the validation started to fail with the following exception:
```
Caused by: ElasticsearchStatusException[method [HEAD], host [https://XXX:1234], URI [/], status line [HTTP/1.1 403 Forbidden]]; nested: ResponseException[method [HEAD], host [https://XXX:1234], URI [/], status line [HTTP/1.1 403 Forbidden]];
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1680)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403)
at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:677)
at …
```

CCMSG-1181: Updated validateConnection to not fail if user doesn't have monitor permission.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java

The Elasticsearch sink fails if the Elasticsearch URL has a trailing `/` 
Strip the ending `/` from given connection URLs

CCMSG-917: Elasticsearch sink connector fails if URL has trailing /

---

src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorSslIT.java

After the latest merge to 11.1.x that specified role privileges, the data stream happy path IT failed with the error message 
`org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: Could not execute PUT request. Error response: {"error_code":500,"message":"Elasticsearch exception [type=security_exception, reason=action [cluster:monitor/main] is unauthorized for user [frank]]"}`
In the IT, a user with the `monitor` privilege needs to be added and used when data streams is enabled.

CCMSG-1203: Update Data Stream Happy Path IT to include monitor privilege.

---

src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ValidatorTest.java

Elasticsearch connector version 11.0.x and above must be using Elasticsearch version 7.0.x or above.
Add a validator that ensures the Elasticsearch version is above 7.0.x
This is similar to the version validation done for data streams ([PR](https://github.com/confluentinc/kafka-connect-elasticsearch/pull/525)).
Not backporting or merging into master

CCMSG-947: Add validation to ES connector to check if it's connecting to a compatible ES sink

---

src/main/java/io/confluent/connect/elasticsearch/RetryUtil.java

When we retry failed requests, we don't log the cause of the failure until we exhaust the retries. If the consumer leaves the group before we exhaust the retries, we will never see the cause of the error.
Log every retry attempt with the exception

Add logging for retries

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java

The ES client we are on is from 2019
Upgrade the client to the latest version

Upgrade ES client to latest version

---

pom.xml

Guava is incorrectly marked as scope dependency. The issue won't surface as long as guava is included with CP
Add the compile time dep

MINOR: Re-add Guava as compile time dependency

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java

We need to know what version of ES server our customers are running in cloud so we can determine if it's safe to upgrade
Log ES server version on sink task startup

Log server version on sink task startup

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java

We pint-merged https://github.com/confluentinc/kafka-connect-elasticsearch/pull/562 which sets the ES client to version `7.0.1` on branch 11.0.x. However, we need version `7.9.3` of the ES client on `11.1.x` and forward to support datastreams
Set client back to `7.9.3` to support ES datastreams

Set ES client back to 7.9.3

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java

The existing ES client has a known deadlock issue: https://github.com/elastic/elasticsearch/issues/47599
Upgrade to a newer version of the client with the fix
The client upgrade doesn't seem to bring any incompatible changes based on the client's changelogs.  We will do further testing to validate this before releasing the connector.

Upgrade ES client to 7.9.3

---

pom.xml

Guava was a dependency of the jest client.
We can remove in 11.0.x and newer

MINOR: Remove guava as a dependency

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorNetworkIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchSinkTaskIT.java

When individual records in a bulk batch fail to be indexed, we still mark them as processed in OffsetTracker. 
These batches are going to be retried but offsets should not be committed past the failing records.
Update logic to avoid marking them as processed.
Patch latest minor release (11.1)
Safe to rollback.

CCMSG-1376: offsets are marked as processed for individual record failures

---

src/main/java/io/confluent/connect/elasticsearch/OffsetTracker.java
src/main/java/io/confluent/connect/elasticsearch/SyncOffsetTracker.java

Release dry-run fails:
```
mvn -Pjenkins -f kafka-connect-elasticsearch --batch-mode -DdryRun=true -DskipTests=false -Darguments=-DskipTests=false '-DpreparationGoals=clean install javadoc:javadoc' release:prepare
...
21:09:15  [INFO] [INFO] ------------------------------------------------------------------------
21:09:15  [INFO] [INFO] BUILD FAILURE
21:09:15  [INFO] [INFO] ------------------------------------------------------------------------
21:09:15  [INFO] [INFO] Total time:  11:51 min
21:09:15  [INFO] [INFO] Finished at: 2021-11-04T04:09:15Z
21:09:15  [INFO] [INFO] ------------------------------------------------------------------------
21:09:15  [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:javadoc (default-cli) on project …
```

MINOR: Fix Javadoc warnings.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

This change https://github.com/confluentinc/kafka-connect-elasticsearch/pull/589 introduced a new configuration parameter - `flush.synchronously`, the default value was set to `true` to avoid a breaking change.
We released this change in a minor release - `v11.1.4`.
But, the synchronous mode has worse performance than asynchronous and it's only needed for a subset of users, who use ES sink with routing SMTs(those that mutate the topic's name).
Original discussion - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/589/files#r735739916
Make asynchronous mode default(`flush.synchronously`=`false`) and have a major release, since this is a breaking change for users, who have routing SMTs.
Doing a major `12.0.0` release.

Use a synchronous flush by default.

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java

Resent or out-of-order records for a given topic who have their versions set externally by the ES connector to the topic offset of the message are generating warnings and being added to the DLQ.  This isn't desired because the nature of the offset mismatch dictates that the record is obsolete anyway and may simply being resent when connect is restarted (which is the case which was seen and reproduced).
For externally-versioned topic records, simply log to debug log and do not send to DLQ.
Reproduction via rolling back offset to zero and bringing connect back up, in which case, topics will be resent with "old" versions, which are <= the version in ES.  dlq topic record s are generated.
After change, no dlq topic records are generated.
This re-send of "old" topic record versions are …

External version (topic offset) conflict records should skip DLQ

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

It was seen in a couple of 11.1.x integration tests that # responses can be larger than # requetss.  This check already exists in the 11.1.x codebase, so backported this "idx" logic to 11.0.x.  
I looked into trying to bring in the IT from 11.1.x, but it would pull in a lot of other changes, which seemed too drastic, since the logic change in this PR is isolated.

Add logic check seen in 11.1.x IT for # responses > # requests

---

pom.xml

Security team uncovered a vulnerability for log4j v2.14.0 (RCCA-5119). versions 2.15.0 or more are good to use.
The log4j dependency is coming as transitive dependency from `org.elasticsearch:elasticsearch`.
Overridden the log4j dependency coming from `org.elasticsearch:elasticsearch` by explicitly adding v2.15.0.

Bump up the log4j dependency

---

pom.xml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046
Update log4j to 2.16.0.
Similar to https://github.com/confluentinc/kafka-connect-elasticsearch/pull/604
Release a new 11.1.x
Backwards compatible.

CCMSG-1548 - Update log4j to 2.16.0

---

README.md

The log has lots of maven-release-plugin and Jenkins automatically generated commits. This makes it difficult to understand or communicate the history of real changes.
There is a Changelog on the Confluent website. This adds a link to the existing Changelog.
Click on the link.

Add link to Changelog

---

src/main/java/io/confluent/connect/elasticsearch/Validator.java

The `ConfigCallbackHandler` has a set of initialisation steps in `customizeHttpClient` which uses some of the configs. If any of the configs are incorrect It will bubble up an uncaught exception in the validator while creating the `HighLevelRestClient`, which internally initialises the handler. The validation will fail with an internal server error. Example
```
{"error_code":500,"message":"Failed to load SSL keystore  of type JKS"}
```
Although the error message is returned this should ideally have the correct response code and proper formatted output.
```
{"error_code":400,"message":"Connector configuration is invalid and contains the following 1 error(s):\nFailed to create client to verify connection. Error: Failed to load SSL keystore  of type JKS\nYou can also find the above list of …
```

FIX: Invalid configs can lead to validation throwing a 500 error. 

---

src/main/java/io/confluent/connect/elasticsearch/Validator.java

Cherry pick https://github.com/confluentinc/kafka-connect-elasticsearch/pull/626 to 11.1.x.

FIX(cherry-pick): Invalid configs can lead to validation throwing a 500 error.

---

src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorNetworkIT.java

For whatever reason, this test only fails in CI, and not every time.  Something weird with WireMock.

Minor: Fix flaky test

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/Mapping.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticSearchMockUtil.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java

Upgrade ElasticSearch client from 7.15.2 to 7.16.3 in order to fix CVE with lucene-core
Most code here comes from similar @avocader PR : https://github.com/confluentinc/kafka-connect-elasticsearch/pull/596

CCMSG-1394: Upgrade lucene-core to fix CVE.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/RetryUtil.java

lcc-gq1xgm Elasticsearch Sink Connector getting document already exists errors
Enabling more logging to understand the NPE

RCCA-7507 : Adding some more logs to understand the exception.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

inc-lcc-gq1xgm-elasticsearch-sink-connector-getting-document-already-exists-err
Due to ES version compat issue, we are seeing a lot of reprocessing error in bulk processing , hence switching off the DLQ mechanism for datastream until we roll out ES 8 compatibility.
since ES 8 is not yet compatible, it throws NPE while processing bulkrequests response and due to bulk req failure , retry mechanism will get triggered and client would try to index already processed records which triggers "INTERNAL version conflict for operation CREATE" error and successfully indexed records will also get redirected to DLQ
1. setup ES 8.x.x
2. start datagen connector to send data to a topic x.
3. start ES connector to read from x with following config :
{
"name": "ElasticsearchSinkConnectorConnector_0", …

RCCA - 7507  :  inc-lcc-gq1xgm-elasticsearch-sink-connector-getting-document-already-exists-err

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

Reverts confluentinc/kafka-connect-elasticsearch#643
changes need to be merged to 11.1.x

Revert "RCCA - 7507  :  inc-lcc-gq1xgm-elasticsearch-sink-connector-getting-document-already-exists-err"

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

inc-lcc-gq1xgm-elasticsearch-sink-connector-getting-document-already-exists-err
Due to ES version compat issue, we are seeing a lot of reprocessing error in bulk processing , hence switching off the DLQ mechanism for datastream until we roll out ES 8 compatibility.
since ES 8 is not yet compatible, it throws NPE while processing bulkrequests response and due to bulk req failure , retry mechanism will get triggered and client would try to index already processed records which triggers "INTERNAL version conflict for operation CREATE" error and successfully indexed records will also get redirected to DLQ
setup ES 8.x.x
start datagen connector to send data to a topic x.
start ES connector to read from x with following config :
{
"name": "ElasticsearchSinkConnectorConnector_0",
"config": { …

RCCA - 7507 : inc-lcc-gq1xgm-elasticsearch-sink-connector-getting-document-already-exists-err 

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

If a non json object is preset in the payload, during data stream insert we end up throwing a `ClassCastException`, while trying to insert the record timestamp if not user given timestamp field is not used. 
Note that if the user is trying to obtain the timestamp from the payload the `jsonNode.has` condition returns null if `jsonNode` is not an `ObjectNode` so the cast is not executed. In such cases, it will most likely fail to be inserted as ES only supports Json Objects as top level elements. This is the current behaviour and is left unchanged. 
Do an explicit check and throw a data exception if not an object node. Also in the previous condition if the json node does not have the user given timestamp field the resulting record may be skipped entirely so added some debug statements for …

CCMSG-2073: Throw data exception when non json object payload is present.

---

pom.xml

Confluent-log4j has been deprecated and we will use reload4j.
Modify dependency.
All CP
Those are test dependencies and no additional tests are written for this PR

CC-17744:Switch from confluent-log4j to reload4j [5.4 and 5.5]

---

pom.xml

revert back to confluent-log4j because parent common is fixed (not SNAPSHOT version) , and it doesn't have reload4j version tagged.

revert back to confluent-log4j because parent common is fixed

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosIT.java
src/test/resources/basic/elasticsearch.yml
src/test/resources/both/elasticsearch.yml
src/test/resources/both/start-elasticsearch.sh
src/test/resources/kerberos/elasticsearch.yml
src/test/resources/none/elasticsearch.yml
src/test/resources/none/instances.yml
src/test/resources/ssl/Dockerfile
src/test/resources/ssl/elasticsearch.yml
src/test/resources/ssl/start-elasticsearch.sh

The current version of the connector does not support  ES 8 and above. 
The High level rest client 7.17 has a compatibility mode which adds some headers to work with ES 8. When using ES 8 and above set this compatibility mode as true. 
Although elastic does not explicitly say that the HLRC in compatibility mode won't work with older elastic versions (7.11 and lower) they do mention [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html) that, under compatibility mode HLRC can also work with 7.11 and higher versions. Its best to only enable compatibility mode only with major version as 8 and above. 
The connector already the ability to retrieve the version so we are using it to selectively turn on compatibility mode support (or …

CCMSG-1958: Elasticsearch 8 support through compatibility mode.

---

src/main/java/io/confluent/connect/elasticsearch/Mapping.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

The connector converts bigdecimal data types to double types. However during the creation of the mapping, the default value of the bigdecimal is simply casted to a double value. This ends up causing a class cast exception if the bigdecimal has a default value. 
Use the correct way to convert to a a double value given in this PR.

CCMSG-2140: Handle bigdecimal defaults.

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java

If empty ssl truststore/keystore configs are given in the configuration it fails to create the ssl context.
If such configs are preset ignore them while creating the ssl context.

Ignore empty ssl truststore/keystore configs.

---

pom.xml

https://confluentinc.atlassian.net/browse/CCMSG-2220
Updated jackson dependency to resolve CVE-2022-42003 and CVE-2022-42004
```
➜  connect-elasticsearch-sink git:(master) ✗ CONNECTOR_ZIP=/Users/ajain/projects/kafka-connect-elasticsearch/target/components/packages/confluentinc-kafka-connect-elasticsearch-11.1.14-SNAPSHOT.zip ./elasticsearch-sink.sh
13:53:12 ℹ️ 💫 Using default CP version 7.3.0
13:53:12 ℹ️ 🎓 set TAG environment variable to specify different version, see https://kafka-docker-playground.io/#/how-to-use?id=🎯-for-confluent-platform-cp
13:53:15 ℹ️ 👷🛠 Re-building Docker image vdesabou/kafka-docker-playground-connect:7.3.0 to include confluentinc/kafka-connect-elasticsearch:latest
[+] Building 24.3s (6/6) FINISHED …
```

CCMSG-2220: Updated jackson dependency to resolve CVE-2022-42003 and CVE-2022-42004

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

https://confluentinc.atlassian.net/browse/CC-19730
https://confluent.slack.com/archives/C04V57GCUCS/p1679999708348829?thread_ts=1679509372.002709&cid=C04V57GCUCS
-  Tested via docker playground
Logs before log.sensitive.data is enabled: <img width="1067" alt="Screenshot 2023-03-29 at 5 09 54 PM" src="https://user-images.githubusercontent.com/121012039/228527591-e8ca822d-e573-4b5b-9fc6-b9b0afb6badc.png">
Logs after log.sensitive.data is enabled: <img width="1106" alt="Screenshot 2023-03-29 at 5 11 40 PM" src="https://user-images.githubusercontent.com/121012039/228527771-ffa78618-038b-474a-904c-8b3ee652f2e0.png">

[CC-19730] Revert to old logging behavior via optional config param

---

pom.xml

${confluent.version} is absent in common 6.2.3. 
Use ${io.confluent.common.version} instead.

fix confluent-version

---

Jenkinsfile

https://github.com/confluentinc/connect-comprehensive-test-framework/pull/3
Enabling Upgrade Connector Test. For each PR and merge commit a build will trigger on connect-comprehensive-test-framework Jenkins, which will run the latest tag connector for that ff branch and the PR changes, mimicking the upgrade scenario.
https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/kafka-connect-elasticsearch/view/change-requests/job/PR-705/5/
Auto triggered a build on connect-comprehensive-test-framework
https://jenkins.confluent.io/job/confluentinc/job/connect-comprehensive-test-framework/job/master/12/consoleFull

Adding upgrade test for ElasticSearch

---

Jenkinsfile
pom.xml

https://confluentinc.atlassian.net/browse/CC-20333
Fixed to 2.15.0 version 
- Docker Playground
```
Creating Elasticsearch Sink connector (Elasticsearch version is 7.0.0)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   634  100   334  100   300   5220   4688 --:--:-- --:--:-- --:--:-- 10745
{
"name": "elasticsearch-sink",
"config": {
"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
"tasks.max": "1",
"topics": "test-elasticsearch-sink",
"key.ignore": "true",
"connection.url": "http://elasticsearch:9200",
"name": "elasticsearch-sink"
},
"tasks": [
{
"connector": "elasticsearch-sink",
"task": 0
}
],
"type": "sink"
}
Sending messages to topic test-elasticsearch-sink
11:16:31 ℹ️ …
```

[CC-20333] CVE fix for jackson package

---

pom.xml

The documentation in the POM is reflected confluent hub. The current documentation lists out all the versions supported and this has caused some confusion in customers as not all version of the connector supports all ES versions.
Remove the listing of all versions and redirecting them to the documentation for more details.

Remove the explicit listing of all supported ES versions.

---

pom.xml

Connector fails with payloads > 5MB
Bump up jackson dependency to include the following fix https://github.com/FasterXML/jackson-core/commit/0484754660f6576667581fbe55fb4da325633953

CC-22326 | Bump up jackson version to increase max string value length from 5 to 20 million chars

---

pom.xml

Fix CVE-2023-31418 and CVE-2023-43642
Update elastic search client version and io.confluent:common to fix snappy-java
The fix will be released to CP first and then fixed in cloud.
The patch will be backported to older branches after some additional fixes.

Bump elastic search client and kafka dependencies

---

Jenkinsfile
pom.xml
sonar-project.properties

- Updated the reporting phase to verify, to use the jacoco-aggregated.exec 
- Enabled Sonarqube quality check on PRs
Job Failing with 
`Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 61`
Added - nodeLabel = 'docker-oraclejdk8'

CC-23123: Enabled SonarQube Quality Check

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

Introduce optional external.version.header config to use for ES external version instead of kafka offset for non-datastream indices
After changing an index mapping, we need to reindex.  To do this, we create a new index, run a batch job with all the existing input documents, while at the same time streaming realtime updates, ensuring we do not miss any documents.  Today both can't run at the same time because we might overwrite a new streamed update with a batch index.
ES external versioning can be used to compare document versions for idempotency.  We will be able to pull a version out of the document into a kafka header and use the same version in the batch job.  We choose header so that deletes with null values are also idempotent.
- [ x] yes
There are a couple of other uses cases that …

Introduce optional external.version.header config

---

.semaphore/semaphore.yml
Jenkinsfile
sonar-project.properties

These changes will be pint merged automatically when this PR is merged, but be on the lookout for automated PRs [like this one](https://github.com/confluentinc/stream-catalog-connect-collibra/pull/24) in case pint runs into merge conflicts.
https://confluentinc.atlassian.net/browse/CC-23524
1) Deletes the Jenkinsfile.
2) Adds generate_connect_changelogs to service.yml
3) Applies latest run of service-bot
[Read the background and motivation](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3033867557/CI+System+Migration+Jenkins-+Semaphore#Background-and-Motivation)  
Please merge this PR ASAP because we plan on shutting down Jenkins by the end of the year.

Migration: Jenkins -> Semaphore

---

pom.xml

The semaphore build is failing pulling the docker images of some packages
As suggested by 
@sp-gupta  updating this package of test-containers for the build fix

Build Failures fix

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

Changes: 
- Only exceptions from Elasticsearch will be logged in DLQ and all connector level errors will be logged as before. 
- When behavior.on.malformed.documents is set to:
IGNORE - Report errors to DLQ and the connector keep running and processes other records.
FAIL - Report errors to DLQ and the connector fails.
- Support for log.sensitive.data is removed. In case of any errors, the log points the customer to check DLQ topic for errors.
- Since this affect UX for on-prem customers, it will be released as a minor version change.

[CC-27487] Error Reporting in Elasticsearch via Errant Reporter

---

pom.xml

Refer to these tickets for details: 
https://confluentinc.atlassian.net/browse/CC-28348
https://confluentinc.atlassian.net/browse/CC-28219
Maven output
```
mvn dependency:tree -Dincludes=org.eclipse.parsson:parsson,org.elasticsearch:elasticsearch
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.version: 13.6
[INFO] os.detected.version.major: 13
[INFO] os.detected.version.minor: 6
[INFO] os.detected.classifier: osx-aarch_64
[INFO]
[INFO] --------------< io.confluent:kafka-connect-elasticsearch >-------------- …
```

Update ES version (#5)

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

Original PR - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/742
PR to expose this config on cloud - https://github.com/confluentinc/kafka-connect-elasticsearch-private/pull/43
Tested using docker playground
**Case 1: correct data stream namespace**
connector configs -
```
{
"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
"tasks.max": "1",
"topics": "test-elasticsearch-sink",
"key.ignore": "true",
"connection.url": "*********",
"connection.username": "********",
"connection.password": "********",
"data.stream.namespace": "ssaraswat${topic}"
}
```
result - 
```
12:46:10 ℹ️ ####################################################
12:46:10 ℹ️ ✅ RESULT: SUCCESS for elasticsearch-sink.sh (took: 2min 10sec - )
12:46:10 ℹ️ …
```

Add 'data.stream.namespace' configuration property

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/Validator.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

Original PR - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/752
PR for template changes - https://github.com/confluentinc/kafka-connect-elasticsearch-private/pull/46
Changed type of the data stream as `String` from `DataStreamType` to support custom inputs.
Created an index template for the data stream traces-testdataset-ssaraswat: 
```
curl -X PUT "*****/_index_template/traces-testdataset-template" \
-u ****:****** \
-H 'Content-Type: application/json' \
-d '{
"index_patterns": ["traces-testdataset-*"],
"data_stream": {},
"template": {
"settings": {
"number_of_shards": 1
},
"mappings": {
"properties": {
"@timestamp": {
"type": "date"
},
"message": {
"type": "text"
}
}
}
},
"priority": 100
}'
```
Connector config -
```
{
"connector.class": …
```

Allow custom DataStream types

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java
src/test/java/io/confluent/connect/elasticsearch/integration/BaseConnectorIT.java

https://confluentinc.atlassian.net/browse/CC-31025: 
In kafka 7.9.0, the class `org.apache.kafka.common.network.Mode` class was refactored to `org.apache.kafka.common.network.ConnectionMode`,
causing connectors to fail with a `ClassNotFoundError` during startup.
Upgrade parent common to 7.9.0.
Replace `Mode` with `ConnectionMode`
Followed similar short term fixes as done in https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/4008607989/2025-01-06+Connect+Cloud+Release+Issues

CC-31025: Upgrade kafka to 7.9.0

---

pom.xml

`common` versions 7.0.15+ do not bring in `distributionManagement`.
They are necessary for the build when releasing the connector.
This has happened before - https://confluent.slack.com/archives/C04GUEGCNG0/p1724936392760469
Add `distributionManagement` explicitly.
Reset version to 15.0.0

Add missing distributionManagement

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientSslTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTestBase.java

The tests in this class were failing frequently, and it seemed to be due to test setup.
The test setup creates an Elasticsearch container, used by all the tests.
Except, one of the tests `testSsl`, so it re-creates the container with SSL enabled.
There seems to be some issue with this - the other tests sometimes end up using the container with SSL
Example run - https://semaphore.ci.confluent.io/jobs/084e28ec-fad2-43eb-a8a2-e40d0fcc0a05/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902&test_id=4a7aece7-5cab-3669-bf09-3c2e177c2c7a
Move `testSsl` to a different class for isolation.

Split test class to solve flakiness
