confluentinc/kafka-connect-elasticsearch

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

Support optional & default values when pre-processing schemas & values	

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTestBase.java

Fix topic index override

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java

Allow for multiple Elasticsearch HTTP URLs

---

docs/elasticsearch_connector.rst

@shikhar this PR documents the known limitation with talking to a secured ES instance.  Can you review?

security limitation docs

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/Mapping.java
src/test/java/io/confluent/connect/elasticsearch/MappingTest.java

Tweaked version of #50 with test

CC-392: Fix mapping existence check

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/IndexableRecord.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchWriterTest.java

CC-393: don't use offset as document version when key.ignore=true

---

docs/changelog.rst

3.3.0-changelog

---

docs/configuration_options.rst
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

Signed-off-by: Arjun Satish <arjun@confluent.io>

CC-1372: Add configuration options for read and connect timeouts

---

docs/configuration_options.rst

https://confluentinc.atlassian.net/browse/DOCS-443

DOCS-443 - Fix broken header tag

---

docs/configuration_options.rst
docs/elasticsearch_connector.rst
docs/index.rst

https://confluentinc.atlassian.net/browse/DOCS-647

Add GH repository info to docs

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

Merge changes from #275 into 5.0.x

Merge 275 into 5.0.x

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTask.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchWriter.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

Merge changes from #275 into 5.2.x

Merge 275 into 5.2.x

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

CC-7147: set the max connection per route config for client

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

follow up PR on #277
thank you @sslavian812

CC-7644: Add support for http(s) proxy

---

src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

the connector used non-public AK APIs to handle SSL configuration. AK 2.6 removed the non-public APIs and introduced a public one. The consequence is that the connector is not forwards compatible with newer AK versions.
Use reflection to determine which AK version is on the Connect worker and use the appropriate API for that version
RabbitMQ connector 
manually verified forward and backward compatibility by configuring SSL for CP 5.2.5-SNAPSHOT (AK 2.2), CP 5.5.0 (AK 2.5) and CP 6.0.0-SNAPSHOT (AK 2.6) to hit all 3 apis and logical branches.
verified that integration test still passes
backport to `5.2.x` where SSL feature was first introduced

CC-9455: address SslFactor backwards/forwards compatibility

---

pom.xml

Preparing for the first independent release
Choose a released version of parent pom (confluentinc/common)
Lands in 10.0.x branch and newer, which will be independent release branches

Update and pin version of confluent common to 6.0.0

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClientTest.java

CC-10923: add reasonable validators for number configs (#456)

---

checkstyle/suppressions.xml

MINOR: fix build

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfigTest.java

adding a null check when validating list of urls

---

src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java

add IT for upsert
backport to `5.4.x`

MINOR: add IT for upsert

---

pom.xml

#468 brought in ES dependencies that contain CVEs, twistlock PR check shows clean
pin the CVE dependencies

CC-13030: fix common codec and snakeyaml CVEs

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchSinkTaskTest.java

MINOR: Fix semver test missing case

---

pom.xml

jackson databind is bringing in a CVE
pin jackson databind to a clean version
backport to `11.0.x` where this CVE is being reported

CCMSG-449: fix jackson databind CVE

---

pom.xml

https://confluentinc.atlassian.net/browse/DOCS-7071
Update documentation URL paths

MINOR: Update docs URLs

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java

MINOR: fix log messsage

---

pom.xml

Update the Confluent Hub support summary for the connector.

Update supportSummary for ElasticSearch Sink

---

pom.xml

MINOR: Upgrade patch version of ES and Lucene for tests prior to 11.0.x

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java

Fix Minor Formatting Issues in Data Stream.

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchHelperClient.java

This reverts commit 0ca659eba95e7d460bcdf5f89a4292d5457a8f09.
Client upgrade may cause problems with customers on older ES servers
Revert client upgrade for now

Revert "Upgrade ES client to latest version (#557)"

---

src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/helper/ElasticsearchContainer.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorKerberosWithSslIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorSslIT.java

The `ElasticsearchConnectorSslIT` integration test is broken:
```
mvn clean test integration-test
...
[INFO] Running io.confluent.connect.elasticsearch.integration.ElasticsearchConnectorSslIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in io.confluent.connect.elasticsearch.integration.ElasticsearchConnectorSslIT
[ERROR] io.confluent.connect.elasticsearch.integration.ElasticsearchConnectorSslIT  Time elapsed: 0.006 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
at io.confluent.connect.elasticsearch.integration.ElasticsearchConnectorSslIT.setupBeforeAll(ElasticsearchConnectorSslIT.java:55)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
at …
```

CCMSG-1239: Fix ElasticsearchConnectorSslIT.

---

pom.xml

Outdated dependencies
Upgrade to newer versions

CCMSG-1022: Upgrade jackson dataformat cbor to 2.11.4 and parent to 6.0.3

---

pom.xml

Client requested update to latest version of log4j
Update log4j to latest (2.17.1)
New patch release

Update log4j to latest (2.17.1)

---

pom.xml

CCMSG-1725 upgraded jackson-databind to resolve CVE

---

pom.xml

CCMSG-1978 elastic search version upgrade

---

pom.xml

CCMSG-1978 pom snapshot version update

---

licenses.html
pom.xml

Snakeyml has a vulnerability in the way it loads which can lead to RCEs. More info here https://securitylab.github.com/research/swagger-yaml-parser-vulnerability/. 
Since it's a transitive dependency on a submodule of ES seeing if we can exclude this from the connector.

CCMSG-1698: Remove snakeyml dependency

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

ElasticSearch Connector is reporting exceptions with customer data. We need to find mechanism to prevent customer data to be reported in our logs.
https://confluentinc.atlassian.net/browse/CCMSG-2395
Connect Runtime [Log Reporter](https://github.com/confluentinc/ce-kafka/blob/master/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/errors/LogReporter.java#L66) logs everything under the context. This is why we are even seeing customer DLQ logs in OpenSearch.
Checked all the APIs under `response.getFailure()` for what they are returning.
The APIs don't provide enough capability to drill down and log the exception explicitly without previewing any customer data.
After careful consideration, we are opting Status, Index and Doc Id (from the ElasticSearch response) to be logged for …

[CCMSG-2395] Restrict Customer data logging to Confluent infra

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java

Merge conflict Resolution from 11.0.x to 11.1.x

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

Merge Conflict Resolution (from 11.0.x to 11.1.x)

---

pom.xml

Merge Conflict Resolution (from 12.0.x to 13.0.x)

---

pom.xml
src/test/java/io/confluent/connect/elasticsearch/integration/BaseConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorBaseIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorDataFormatIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchConnectorSecureIT.java
src/test/java/io/confluent/connect/elasticsearch/integration/ElasticsearchContainer.java

Testing JSON_SR, PROTOBUF, AVRO formats with embedded schema-registry-cluster
All connectors which support schema-based data

[CC-19402] SR testing using RestApp

---

pom.xml

Added limits to fail the build if coverage is not met for Jacoco Report

---

pom.xml

CC-21741 : Added Jacoco check to failed the build if coverage isn't met

---

pom.xml

Fixed Jacoco thresholds causing the Jenkins build to fail

---

src/main/java/io/confluent/connect/elasticsearch/DataConverter.java
src/main/java/io/confluent/connect/elasticsearch/ElasticsearchSinkConnectorConfig.java
src/test/java/io/confluent/connect/elasticsearch/DataConverterTest.java

Merge 11.0.x to 11.1.x

---

pom.xml

CVE - https://confluentinc.atlassian.net/browse/CONMON-529
Upgraded the es.version to 7.17.14
Dependency Tree :-
Local Testing
Using the CP, have setup the local elasticsearch-sink connector with the upgraded es.version
Have followed the same instructions as per the public doc - https://docs.confluent.io/kafka-connectors/elasticsearch/current/overview.html
The output from the test-elasticsearch-sink topic is as follows:-

upgraded the es.version to fix CVE

---

src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java

https://confluentinc.atlassian.net/browse/CC-25275
Change log level to DEBUG for the concerned log line.

[CC-25275] Change log level to DEBUG

---

pom.xml

Merge Conflict Resolution (from 10.0.x to 11.0.x)

---

pom.xml

Merge Conflict Resolution (from 13.0.x to 13.1.x)

---

pom.xml

Merge Conflict Resolution (from 14.0.x to master)

---

.semaphore/semaphore.yml
pom.xml

Revert due to an issue in publishing of artifact

Revert 14.1.0 release

---

pom.xml

Merge Conflict Resolution (from 14.1.x to master)

---

pom.xml

Fix Release issue

---

pom.xml

update tag version

---

pom.xml

Merge Conflict Resolution (from 14.0.x to 14.1.x)

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/BaseConnectorIT.java

Resolve ClassNotFound issue

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/bulk/BulkResponse.java
src/main/java/io/confluent/connect/elasticsearch/jest/JestElasticsearchClient.java

Refer to these JIRA for details: https://confluentinc.atlassian.net/browse/CC-30686?focusedCommentId=3611266

Bump common version to 6.0.15

---

pom.xml
src/main/java/io/confluent/connect/elasticsearch/ConfigCallbackHandler.java
src/test/java/io/confluent/connect/elasticsearch/ElasticsearchClientTest.java
src/test/java/io/confluent/connect/elasticsearch/integration/BaseConnectorIT.java

Revert 14.2.x branch release changes in master

---

pom.xml

Incorrect version format was used when creating feature branch.
Fix the version in master

Fix version in pom

---

pom.xml

Update artifact version to 15.0.0

CC-31025: Update snapshot version to 15.0.0

---

.semaphore/semaphore.yml

Ubuntu migration
